{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'bgTemplate',
          'title':u'Standard Template with full menus',
          'size':(400, 300),
          'statusBar':1,
          'backgroundColor':(218, 218, 218),

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileNew',
                   'label':'&New\tCtrl+N',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileOpen',
                   'label':'&Open\tCtrl+O',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSave',
                   'label':'&Save\tCtrl+S',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSaveAs',
                   'label':'Save &As...',
                  },
                  {'type':'MenuItem',
                   'name':'fileSep1',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuFilePageSetup',
                   'label':'Page Set&up...',
                  },
                  {'type':'MenuItem',
                   'name':'menuFilePrint',
                   'label':'&Print...\tCtrl+P',
                  },
                  {'type':'MenuItem',
                   'name':'menuFilePrintPreview',
                   'label':'Print Pre&view',
                  },
                  {'type':'MenuItem',
                   'name':'fileSep2',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit\tAlt+X',
                   'command':'exit',
                  },
              ]
             },
             {'type':'Menu',
             'name':'Edit',
             'label':'&Edit',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuEditUndo',
                   'label':'&Undo\tCtrl+Z',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditRedo',
                   'label':'&Redo\tCtrl+Y',
                  },
                  {'type':'MenuItem',
                   'name':'editSep1',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditCut',
                   'label':'Cu&t\tCtrl+X',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditCopy',
                   'label':'&Copy\tCtrl+C',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditPaste',
                   'label':'&Paste\tCtrl+V',
                  },
                  {'type':'MenuItem',
                   'name':'editSep2',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditClear',
                   'label':'Cle&ar\tDel',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditSelectAll',
                   'label':'Select A&ll\tCtrl+A',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuHelp',
             'label':'&Help',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuHelpAbout',
                   'label':'&About ...',
                   'command':'doHelpAbout',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'Choice', 
    'name':'MainOptions', 
    'position':(10, 10), 
    'size':(150, -1), 
    'items':[u'Daily', u'Weekly', u'Monthly'], 
    },

{'type':'Calendar', 
    'name':'Calendar', 
    'position':(179, 8), 
    'foregroundColor':(107, 255, 134, 255), 
    },

{'type':'Button', 
    'name':'cmdCancel', 
    'position':(210, 210), 
    'label':u'Cancel', 
    },

{'type':'Button', 
    'name':'cmdOkay', 
    'position':(100, 210), 
    'label':u'Okay', 
    },

] # end components
} # end background
] # end backgrounds
} }
